/**
 * Conteúdo bilíngue (PT/EN) da Câmara de Comércio Brasil–Omã (CTB).
 * Fonte: apresentação institucional oficial "Câmara de Comércio - CTB II".
 */

export type Locale = "pt" | "en";

export const content = {
  pt: {
    meta: {
      title: "CTB — Câmara de Comércio Brasil–Omã",
      description:
        "Câmara de Comércio Brasil–Omã (CTB): conectando potências complementares. Promovemos comércio, investimentos e cooperação institucional entre o Brasil e o Sultanato de Omã.",
    },
    nav: {
      about: "A Câmara",
      countries: "Brasil & Omã",
      services: "Atuação",
      ecosystem: "Ecossistema",
      membership: "Associe-se",
      news: "Notícias",
      contact: "Contato",
    },
    brand: { tagline: "Câmara de Comércio Brasil–Omã" },
    hero: {
      eyebrow: "Brasil · Sultanato de Omã · 2026",
      titleA: "Conectando potências ",
      titleAccent: "complementares",
      titleB: " em um mundo em transformação",
      lead: "A CTB é a ponte institucional entre o Brasil e Omã: promovemos comércio, investimentos e cooperação estratégica, com neutralidade, transparência e segurança jurídica.",
      ctaJoin: "Associe-se à Câmara",
      ctaContact: "Fale conosco",
      motto: "“União e Prosperidade”",
      stats: [
        { n: "US$ 2 bi+", l: "em comércio bilateral anual" },
        { n: "São Paulo · Mascate", l: "presença nos dois países" },
        { n: "Londres · Dubai", l: "ecossistema global integrado" },
      ],
    },
    heroBridge: {
      eyebrow: "Brasil · Sultanato de Omã · 2026",
      titleA: "",
      titleAccent: "Brasil e Omã",
      titleB: " unidos por uma visão de futuro",
      lead: "Conectamos governos, empresas e investidores para fortalecer relações estratégicas, promover comércio, investimentos, inovação e cooperação institucional entre duas nações unidas pela confiança, pela excelência e pela prosperidade compartilhada.",
      ctaJoin: "Associe-se à Câmara",
      ctaLearn: "Saiba mais",
      mottoMain: "União e Prosperidade",
      mottoSub: "Unio et Prosperitas · الاتحاد والازدهار",
    },
    purpose: {
      eyebrow: "Nossa missão",
      titleLine1: "Conectar Nações.",
      titleLine2: "Impulsionar Oportunidades.",
      titleAccent: "Construir Legados.",
      lead: "Promovemos relações estratégicas entre Brasil e Omã por meio do comércio, dos investimentos, da inovação e da cooperação institucional, criando conexões duradouras que fortalecem economias, aproximam culturas e geram prosperidade compartilhada.",
      pillarsEyebrow: "Os cinco pilares da Câmara",
      items: [
        { icon: "handshake", h: "Conectamos", p: "Criamos pontes entre governos, empresas e investidores para transformar oportunidades em relações duradouras." },
        { icon: "chart", h: "Promovemos", p: "Impulsionamos comércio, investimentos e inovação com segurança institucional." },
        { icon: "globe", h: "Fortalecemos", p: "Aproximamos culturas, mercados e lideranças para gerar cooperação de longo prazo." },
        { icon: "scale", h: "Garantimos", p: "Atuamos com ética, conformidade, transparência e segurança jurídica em todas as relações." },
        { icon: "laurel", h: "Prosperamos", p: "Criamos valor compartilhado por meio do desenvolvimento econômico sustentável." },
      ],
    },
    strip: [
      { icon: "globe", h: "Reconhecimento internacional", p: "Governos · Embaixadas · Instituições · Parceiros Estratégicos" },
      { icon: "pin", h: "Cooperação bilateral", p: "Comércio · Investimentos · Inovação · Diplomacia Econômica" },
      { icon: "network", h: "Rede global", p: "Brasil · Omã · GCC · Mercados Internacionais" },
    ],
    about: {
      eyebrow: "Quem somos",
      titleLine1: "Uma associação civil,",
      titleAccent: "sem fins lucrativos,",
      titleLine3: "de caráter institucional.",
      p1: "A CTB — Câmara de Comércio Brasil–Omã é uma associação civil de direito privado, sem fins lucrativos, criada para fortalecer e aprofundar as relações comerciais, econômicas e de investimentos entre as duas nações.",
      p2: "Atuamos com personalidade jurídica própria e plena autonomia administrativa, financeira e patrimonial, sempre pautados pela ética, transparência e neutralidade institucional.",
      pillars: [
        { icon: "globe", h: "Missão", p: "Promover, fortalecer e aprofundar as relações comerciais, econômicas e de investimentos entre o Brasil e Omã." },
        { icon: "scale", h: "Princípios", p: "Atuação baseada na ética, transparência, neutralidade institucional e respeito às legislações de ambos os países." },
        { icon: "bank", h: "Governança", p: "Personalidade jurídica própria, com plena autonomia administrativa, financeira e patrimonial." },
      ],
    },
    moment: {
      eyebrow: "O momento global de 2026",
      title: "Por que agora",
      lead: "A reconfiguração geopolítica e a fragmentação das cadeias globais de suprimento tornaram as parcerias estratégicas baseadas em confiança e neutralidade mais essenciais do que nunca.",
      cards: [
        { icon: "🌐", h: "Contexto", p: "Reconfiguração geopolítica e fragmentação das cadeias globais de suprimento." },
        { icon: "⚡", h: "Desafios", p: "Pressão por segurança alimentar, segurança energética e transição para economias sustentáveis." },
        { icon: "🤝", h: "Oportunidade", p: "Parcerias estratégicas baseadas em confiança e neutralidade tornaram-se essenciais." },
      ],
    },
    countries: {
      eyebrow: "Duas economias, uma sinergia",
      title: "Brasil & Omã",
      lead: "Duas economias complementares. Unidos por oportunidades e um futuro compartilhado.",
      brazil: {
        flag: "🇧🇷",
        name: "Brasil",
        sub: "Protagonismo e resiliência",
        items: [
          { b: "Geopolítica:", t: "voz central do Sul Global e mediador em fóruns como G20 e BRICS+." },
          { b: "Diplomacia ambiental:", t: "matriz energética limpa como “moeda diplomática” na transição climática." },
          { b: "Força econômica:", t: "agronegócio, infraestrutura e energia renovável (hidrogênio verde e eólica offshore)." },
          { b: "Comércio exterior:", t: "exportações projetadas entre US$ 340 e US$ 380 bilhões, com superávit de US$ 70 a 90 bilhões." },
        ],
      },
      oman: {
        flag: "🇴🇲",
        name: "Sultanato de Omã",
        sub: "Estabilidade e visão estratégica",
        items: [
          { b: "Diplomacia:", t: "política de “amigo de todos”, facilitador essencial de diálogos no Oriente Médio." },
          { b: "Geopolítica:", t: "posição invejável fora do Estreito de Ormuz, garantindo segurança energética." },
          { b: "Hub logístico:", t: "portos de Duqm, Sohar e Salalah conectando Ásia, África e Europa." },
          { b: "Vision 2040:", t: "diversificação com foco em turismo, mineração, tecnologia e hidrogênio verde." },
        ],
      },
    },
    partnership: {
      eyebrow: "Uma parceria natural e complementar",
      titleLine1: "Fluxos Comerciais",
      titleAccent: "e Sinergia",
      lead: "O Brasil fornece energia calórica (alimentos) e mineral; Omã fornece os insumos químicos (fertilizantes) e energéticos que sustentam a potência agrícola brasileira. Uma “parceria estratégica silenciosa” que já supera US$ 2 bilhões anuais.",
      flowFrom: {
        flag: "🇧🇷",
        h: "Brasil → Omã",
        p: "Minério de ferro, complexo de proteínas animais (frango e carne) e açúcar.",
      },
      flowTo: {
        flag: "🇴🇲",
        h: "Omã → Brasil",
        p: "Fertilizantes nitrogenados, petróleo refinado e produtos petroquímicos.",
      },
      exampleLabel: "Exemplo prático:",
      exampleText: "a operação da Vale em Sohar como centro de distribuição industrial para o Oriente Médio e Ásia.",
    },
    video: {
      eyebrow: "Vídeo institucional",
      title: "Conheça a CTB",
      lead: "Um retrato da ponte institucional que estamos construindo entre o Brasil e o Sultanato de Omã.",
    },
    services: {
      eyebrow: "Como atuamos",
      titleLine1: "Fomento, Conectividade",
      titleAccent: "e Segurança Jurídica",
      lead: "Uma estrutura completa para viabilizar negócios entre os dois países — do primeiro contato à segurança jurídica das operações.",
      cards: [
        { icon: "handshake", h: "Intercâmbio", p: "Promoção de missões comerciais, fóruns, seminários e feiras de negócios bilaterais." },
        { icon: "trending", h: "Inteligência", p: "Produção de estudos, relatórios e análises setoriais para identificar oportunidades de mercado." },
        { icon: "globetech", h: "Cultura e Tecnologia", p: "Incentivo a iniciativas que facilitem o intercâmbio tecnológico entre os dois países." },
        { icon: "certificate", h: "Certificação", p: "Serviços de certificação de documentos de exportação e certificados de origem." },
        { icon: "bank", h: "Interlocução", p: "Atuação como interlocutora institucional perante autoridades governamentais quando autorizada.", featured: true },
        { icon: "scale", h: "Segurança Jurídica", p: "Centro próprio de Arbitragem e Mediação, com gestão independente, celeridade e imparcialidade." },
      ],
    },
    ecosystem: {
      eyebrow: "Nosso ecossistema estratégico",
      titleLine1: "Uma estrutura",
      titleAccent: "Global Integrada",
      lead: "O sucesso da CTB é sustentado por um ecossistema de empresas e instituições que garantem suporte jurídico, financeiro, operacional e humanitário em escala global.",
      cards: [
        { logo: "/ecosystem/ctb-holdings.png", tag: "Londres", h: "CTB Holdings", p: "Mantenedora global do Grupo, responsável pela governança corporativa e diretrizes estratégicas internacionais." },
        { logo: "/ecosystem/ctb-venture.png", tag: "Trade Finance", h: "CTBX Venture Investment S.A.", p: "Braço especializado em Trade Finance e consultoria em commodities, focado em operações estruturadas." },
        { logo: "/ecosystem/omanbrasil.png", tag: "Inteligência", h: "OmanBrasil", p: "Hub de inteligência comercial: identificação de oportunidades, análise de mercado e intermediação de negócios." },
        { logo: "/ecosystem/fundacao-wahibi.png", tag: "ESG · Impacto", h: "Fundação Wahibi", p: "Pilar de responsabilidade institucional em projetos humanitários, sustentabilidade e desenvolvimento humano." },
      ],
    },
    membership: {
      eyebrow: "Faça parte",
      titleLine1: "Uma ponte para",
      titleAccentLine1: "novas",
      titleAccentLine2: "oportunidades",
      lead: "Torne-se membro e acesse uma rede exclusiva de negócios, inteligência de mercado e segurança jurídica entre o Brasil e Omã.",
      benefits: [
        { icon: "briefcase", text: "Acesso a rodadas de negócios e missões empresariais" },
        { icon: "trending", text: "Relatórios e análises de mercado exclusivos" },
        { icon: "certificate", text: "Suporte em certificação e comércio exterior" },
        { icon: "people", text: "Networking com lideranças dos dois países" },
        { icon: "scale", text: "Acesso ao Centro de Arbitragem e Mediação" },
        { icon: "megaphone", text: "Divulgação da sua empresa nos canais da Câmara" },
      ],
      cta: "Quero me associar",
    },
    membershipPage: {
      hero: {
        eyebrow: "Faça parte",
        title: "Associe-se à Câmara de Comércio Brasil–Omã",
        p1: "Integre uma rede estratégica formada por empresas, investidores, instituições e lideranças comprometidas com o fortalecimento das relações econômicas entre o Brasil e o Sultanato de Omã.",
        p2: "Como associado, sua empresa passa a contar com inteligência de mercado, conexões qualificadas, oportunidades de cooperação e apoio institucional para desenvolver negócios entre os dois países.",
        cta: "Solicitar associação",
        formTitle: "Associe sua empresa",
        form: {
          name: "Nome completo",
          phone: "Telefone",
          email: "E-mail profissional",
          company: "Empresa",
          role: "Cargo",
          sector: "Setor de atuação",
          country: "País",
          message: "Mensagem",
          submit: "Enviar solicitação",
          sending: "Enviando…",
          ok: "Pedido enviado com sucesso. Nossa equipe entrará em contato em breve!",
          err: "Não foi possível enviar. Verifique os campos e tente novamente.",
        },
      },
      tabs: {
        home: "Início",
        overview: "Benefícios",
        understand: "Entenda a Associação",
        reputation: "Reputação",
        support: "Apoio",
        connection: "Conexão",
        expansion: "Expansão",
        extra: "Serviços",
        consulting: "Consultoria",
      },
      overview: {
        eyebrow: "Uma rede de oportunidades",
        title: "Benefícios de ser associado",
        lead: "A associação à Câmara proporciona acesso a um ambiente institucional criado para aproximar mercados, identificar oportunidades e apoiar empresas interessadas nas relações comerciais entre Brasil e Omã.",
        subtitle: "Benefícios principais",
        items: [
          { icon: "network", h: "Conexões empresariais qualificadas", p: "Aproximação com empresas, investidores, fornecedores, compradores e potenciais parceiros nos dois países." },
          { icon: "trending", h: "Inteligência de mercado", p: "Acesso a informações econômicas, análises setoriais e oportunidades relevantes para a tomada de decisões." },
          { icon: "plane", h: "Missões e eventos empresariais", p: "Participação em missões comerciais, fóruns, seminários, encontros institucionais e rodadas de negócios." },
          { icon: "globe", h: "Apoio à internacionalização", p: "Orientação inicial para empresas interessadas em acessar os mercados brasileiro e omanense." },
          { icon: "megaphone", h: "Divulgação institucional", p: "Possibilidade de apresentação da empresa nos canais, eventos e iniciativas da Câmara." },
          { icon: "handshake", h: "Relacionamento institucional", p: "Participação em uma rede de diálogo com associações empresariais, entidades e lideranças dos dois países." },
          { icon: "certificate", h: "Certificado de associado", p: "Documento institucional que reconhece a participação da empresa na rede da Câmara." },
          { icon: "seal", h: "Selo digital de membro", p: "Identificação visual para uso nos canais institucionais da empresa, conforme as regras da Câmara." },
        ],
      },
      understand: {
        eyebrow: "Uma parceria de longo prazo",
        title: "Entenda a Associação",
        p1: "A associação é o vínculo institucional entre a Câmara e empresas, organizações e profissionais que compartilham o interesse em ampliar as relações econômicas entre Brasil e Omã.",
        p2: "Mais do que um programa de benefícios, ela representa a entrada em um ecossistema de cooperação, conhecimento e desenvolvimento de oportunidades.",
        subtitle: "Vantagens da Associação",
        lead: "Ser associado significa ampliar a capacidade de relacionamento da sua empresa, conhecer melhor os dois mercados e participar de iniciativas voltadas ao comércio, aos investimentos e à cooperação bilateral.",
        items: [
          { icon: "pin", h: "Presença bilateral", p: "Atuação voltada à aproximação entre o Brasil e o Sultanato de Omã, com conexões em Brasília, Mascate e outros centros estratégicos." },
          { icon: "network", h: "Rede empresarial internacional", p: "Relacionamento com empresas, investidores, instituições e lideranças interessadas em iniciativas entre os dois países." },
          { icon: "globetech", h: "Conhecimento especializado", p: "Acesso a informações sobre setores estratégicos, ambiente de negócios, oportunidades comerciais e características culturais de cada mercado." },
          { icon: "bank", h: "Apoio institucional", p: "Orientação e facilitação de contatos dentro dos limites institucionais e das atribuições da Câmara." },
        ],
      },
      sections: [
        {
          eyebrow: "Reputação",
          number: "1",
          title: "Fortaleça a presença institucional da sua empresa",
          lead: "Ao integrar a Câmara de Comércio Brasil–Omã, sua empresa passa a fazer parte de uma rede comprometida com ética, transparência, cooperação e desenvolvimento econômico sustentável.",
          items: [
            { icon: "certificate", h: "Certificado institucional de associado", p: "Documento emitido pela Câmara reconhecendo formalmente a participação da empresa em seu quadro associativo." },
            { icon: "seal", h: "Selo exclusivo de membro", p: "Identidade visual destinada às empresas associadas, conforme as normas de uso da marca." },
            { icon: "idcard", h: "Perfil no diretório de associados", p: "Apresentação institucional da empresa no ambiente destinado à rede de membros." },
            { icon: "handshake", h: "Participação em iniciativas da Câmara", p: "Possibilidade de integrar eventos, fóruns, missões e projetos relacionados ao setor de atuação da empresa." },
            { icon: "megaphone", h: "Divulgação de iniciativas relevantes", p: "Compartilhamento de notícias, projetos e oportunidades da empresa, sujeito aos critérios editoriais da Câmara." },
            { icon: "calendar", h: "Acesso ao calendário institucional", p: "Informações antecipadas sobre eventos, encontros, missões comerciais e atividades da Câmara." },
          ],
        },
        {
          eyebrow: "Apoio",
          number: "2",
          title: "Acesse oportunidades entre Brasil e Omã",
          lead: "A Câmara reúne conhecimento, conexões e iniciativas para ajudar empresas a compreender os mercados e identificar caminhos de cooperação entre os dois países.",
          items: [
            { icon: "trending", h: "Dados e indicadores econômicos", p: "Informações sobre comércio bilateral, setores prioritários, tendências e oportunidades emergentes." },
            { icon: "globe", h: "Conhecimento dos mercados locais", p: "Conteúdos sobre ambiente empresarial, práticas comerciais, aspectos culturais e características de cada país." },
            { icon: "handshake", h: "Facilitação de conexões", p: "Identificação e aproximação inicial com empresas, organizações e possíveis parceiros comerciais." },
            { icon: "calendar", h: "Presença em eventos estratégicos", p: "Acesso a fóruns, conferências, seminários, encontros empresariais e missões institucionais." },
          ],
        },
        {
          eyebrow: "Conexão",
          number: "3",
          title: "Amplie sua rede de negócios e parceiros",
          lead: "A Câmara cria ambientes favoráveis ao relacionamento entre empresas brasileiras e omanenses, contribuindo para o surgimento de novas parcerias, projetos e oportunidades comerciais.",
          items: [
            { icon: "people", h: "Matchmaking empresarial", p: "Identificação de empresas com interesses complementares para possíveis reuniões e negociações." },
            { icon: "idcard", h: "Diretório de associados", p: "Acesso às informações institucionais dos membros, respeitando as regras de privacidade e utilização da rede." },
            { icon: "network", h: "Networking bilateral e internacional", p: "Participação em encontros com empresários, investidores, executivos e representantes institucionais." },
            { icon: "megaphone", h: "Visibilidade nos canais da Câmara", p: "Possibilidade de divulgação da empresa, de seus projetos e de suas oportunidades nos canais institucionais disponíveis." },
          ],
        },
        {
          eyebrow: "Expansão",
          number: "4",
          title: "Desenvolva os negócios da sua empresa",
          lead: "A associação proporciona recursos e conexões para apoiar empresas em diferentes etapas de sua expansão internacional.",
          items: [
            { icon: "handshake", h: "Rodadas de negócios", p: "Participação em reuniões organizadas com potenciais compradores, fornecedores, investidores e parceiros." },
            { icon: "plane", h: "Missões empresariais", p: "Integração em delegações e agendas comerciais realizadas no Brasil e em Omã." },
            { icon: "trending", h: "Estudos e análises setoriais", p: "Acesso a conteúdos voltados aos setores com maior potencial de cooperação bilateral." },
            { icon: "briefcase", h: "Apresentação de oportunidades", p: "Divulgação de demandas comerciais, projetos, propostas de investimento e possibilidades de parceria." },
            { icon: "monitor", h: "Seminários e capacitações", p: "Eventos sobre comércio exterior, ambiente regulatório, cultura de negócios, logística e internacionalização." },
            { icon: "people", h: "Cooperação entre associados", p: "Estímulo a projetos conjuntos e à formação de parcerias dentro da própria rede da Câmara." },
          ],
        },
      ],
      extra: {
        eyebrow: "Serviços ao associado",
        title: "Uma estrutura preparada para apoiar sua jornada",
        items: [
          { icon: "mail", h: "Atendimento institucional dedicado", p: "Canal de relacionamento para orientar o associado sobre atividades, eventos e oportunidades da Câmara." },
          { icon: "calendar", h: "Condições especiais em eventos", p: "Benefícios ou condições diferenciadas em determinadas atividades promovidas pela Câmara, quando aplicável." },
          { icon: "bank", h: "Uso de espaços para reuniões", p: "Acesso a ambientes de reunião ou apoio institucional, conforme disponibilidade e regras específicas." },
          { icon: "idcard", h: "Divulgação no diretório empresarial", p: "Inclusão da empresa na área destinada à apresentação dos associados." },
          { icon: "people", h: "Participação em comitês temáticos", p: "Possibilidade de contribuir com grupos de trabalho relacionados a setores e temas estratégicos." },
          { icon: "mail", h: "Recebimento de informativos exclusivos", p: "Boletins com notícias, oportunidades, eventos, missões e informações econômicas." },
          { icon: "calendar", h: "Convites para encontros institucionais", p: "Participação em recepções, reuniões, seminários e agendas promovidas ou apoiadas pela Câmara." },
          { icon: "network", h: "Apoio na identificação de parceiros", p: "Pesquisa inicial e indicação de potenciais empresas ou instituições relacionadas ao objetivo apresentado pelo associado." },
        ],
      },
      closing: {
        eyebrow: "Uma conexão que gera valor",
        title: "Faça parte de uma nova etapa das relações entre Brasil e Omã",
        lead: "Associe sua empresa a uma rede construída para aproximar mercados, fortalecer relações e transformar oportunidades em parcerias duradouras.",
        ctaPrimary: "Quero me associar",
        ctaSecondary: "Fale com nossa equipe",
        quote: "“Conectamos mercados. Aproximamos lideranças. Construímos prosperidade compartilhada.”",
      },
    },
    consultingPage: {
      eyebrow: "Consultoria Internacional",
      title: "Inteligência estratégica para negócios entre Brasil, Omã e o Golfo",
      p1: "Nossa equipe reúne especialistas em comércio internacional, inteligência de mercado, investimentos e relações institucionais para apoiar empresas que desejam expandir suas operações nos países do Golfo.",
      p2: "Mais do que consultoria, entregamos estratégia, conexões qualificadas e soluções personalizadas para acelerar negócios internacionais.",
      whyTitle: "Por que escolher nossa consultoria?",
      why: [
        "Uma estrutura criada para gerar resultados internacionais.",
        "Atendimento personalizado por especialistas.",
        "Planejamento estratégico de entrada em novos mercados.",
        "Inteligência comercial baseada em dados reais.",
        "Rede institucional construída entre Brasil, Omã e Oriente Médio.",
      ],
      solutionsTitle: "Soluções de acordo com o estágio da sua empresa",
      blocks: [
        {
          number: "1",
          icon: "briefcase",
          title: "Consultoria Estratégica Personalizada",
          lead: "Cada empresa possui objetivos diferentes.",
          body: "Desenvolvemos projetos sob medida para internacionalização, investimentos, exportação, importação e expansão empresarial.",
          chipsLabel: "Inclui",
          chips: ["Planejamento internacional", "Estratégia comercial", "Estudos personalizados", "Inteligência competitiva", "Roadmap de expansão"],
        },
        {
          number: "2",
          icon: "trending",
          title: "Empresas iniciando no comércio internacional",
          lead: "Para empresas que desejam iniciar suas operações internacionais com segurança.",
          body: "Realizamos estudos completos para identificar oportunidades comerciais e construir um plano consistente de internacionalização.",
          cardsLabel: "Serviços",
          cards: [
            { h: "Inteligência de Mercado", p: "Análise completa do mercado-alvo, concorrência, demanda e potencial comercial." },
            { h: "Mercados Prioritários", p: "Identificação dos países mais promissores para seu produto ou serviço." },
            { h: "Estratégia de Precificação", p: "Definição de preços competitivos considerando logística, impostos, concorrência e posicionamento internacional." },
          ],
        },
        {
          number: "3",
          icon: "scale",
          title: "Compliance e Regulamentação Internacional",
          body: "Orientamos sua empresa sobre todas as exigências legais para operar no exterior.",
          chipsLabel: "Inclui",
          chips: ["Regulamentações comerciais", "Requisitos alfandegários", "Documentação internacional", "Certificações obrigatórias", "Compliance comercial"],
        },
        {
          number: "4",
          icon: "ship",
          title: "Empresas exportadoras que desejam entrar no Golfo",
          body: "Para empresas brasileiras que já exportam e pretendem atuar em Omã, Emirados Árabes Unidos, Arábia Saudita, Catar, Kuwait e Bahrain.",
          cardsLabel: "Estudos especializados",
          cards: [
            { h: "Canais de Distribuição", p: "Identificação dos melhores canais de venda, distribuidores e parceiros comerciais." },
            { h: "Adequação Comercial", p: "Orientação sobre embalagem, identidade visual, comunicação e adaptação cultural." },
            { h: "Inteligência Competitiva", p: "Mapeamento de concorrentes, posicionamento e oportunidades de diferenciação." },
            { h: "Rede de Compradores", p: "Identificação de importadores, distribuidores e investidores." },
          ],
        },
        {
          number: "5",
          icon: "globetech",
          title: "Expansão Internacional",
          lead: "Para empresas já presentes no mercado internacional.",
          body: "Desenvolvemos estratégias para ampliar operações e consolidar presença na região do Golfo.",
          chipsLabel: "Serviços",
          chips: ["Estruturação internacional", "Implantação comercial", "Desenvolvimento de parceiros", "Crescimento regional"],
          subBlocks: [
            {
              h: "Abertura de Empresas em Omã",
              p: "Prestamos suporte completo para abertura de empresas no Sultanato de Omã.",
              chipsLabel: "Inclui",
              chips: ["Escolha da estrutura societária", "Licenciamento", "Registro empresarial", "Investimento estrangeiro", "Apoio institucional"],
            },
            {
              h: "Abertura de Empresas nos Emirados Árabes Unidos",
              p: "Assessoria completa para implantação em Free Zones ou Mainland.",
            },
          ],
        },
        {
          number: "6",
          icon: "plane",
          title: "Missões Empresariais",
          lead: "Conectamos sua empresa diretamente aos tomadores de decisão.",
          body: "Organizamos agendas executivas personalizadas conforme os objetivos da empresa.",
          chipsLabel: "Inclui",
          chips: ["Rodadas de negócios", "Reuniões governamentais", "Encontros com investidores", "Visitas técnicas", "Missões comerciais", "Networking institucional"],
        },
        {
          number: "7",
          icon: "monitor",
          title: "Inteligência Internacional",
          body: "Produzimos estudos estratégicos para apoiar decisões de investimento.",
          cards: [
            { h: "Workshops Executivos", p: "Treinamentos sobre cultura de negócios, negociação internacional e oportunidades comerciais." },
            { h: "Relatórios País", p: "Panorama econômico, político, jurídico e comercial dos mercados do Golfo." },
            { h: "Estudos Setoriais", p: "Análises específicas por indústria, identificando tendências e oportunidades." },
          ],
        },
        {
          number: "8",
          icon: "people",
          title: "Business Matchmaking",
          lead: "Conectamos empresas, investidores e oportunidades.",
          body: "Nosso serviço exclusivo aproxima sua empresa dos principais atores econômicos da região.",
          chipsLabel: "Benefícios",
          chips: ["Reuniões qualificadas", "Seleção de parceiros estratégicos", "Apoio institucional", "Networking executivo", "Follow-up comercial", "Acompanhamento das negociações"],
        },
      ],
      closing: {
        title: "Um parceiro estratégico para sua expansão internacional",
        p: "A Câmara de Comércio Brasil–Omã atua como facilitadora de negócios entre empresas brasileiras e o mercado do Golfo, oferecendo inteligência de mercado, conexões institucionais e suporte especializado para transformar oportunidades em resultados concretos.",
      },
      form: {
        eyebrow: "Solicite uma Consultoria",
        title: "Leve sua empresa para um novo patamar internacional",
        lead: "Nossa equipe está pronta para desenvolver uma estratégia personalizada para sua expansão no Sultanato de Omã, Emirados Árabes Unidos e demais países do Conselho de Cooperação do Golfo (GCC).",
        fields: { name: "Nome", company: "Empresa", role: "Cargo", email: "E-mail", phone: "Telefone", country: "País" },
        submit: "Enviar solicitação",
        sending: "Enviando…",
        ok: "Solicitação enviada com sucesso. Nossa equipe entrará em contato em breve!",
        err: "Não foi possível enviar. Verifique os campos e tente novamente.",
      },
    },
    news: {
      eyebrow: "Fique por dentro",
      title: "Notícias & Eventos",
      lead: "Acompanhe as principais iniciativas, eventos e oportunidades que conectam o Brasil e Omã.",
      items: [
        { icon: "calendar", tag: "Lançamento", date: "2026 · Brasília / Mascate", h: "Lançamento Oficial da Câmara de Comércio Brasil–Omã", p: "“Hoje iniciamos uma nova rota de crescimento global. Junte-se à Câmara de Comércio Brasil–Omã.”", link: "/noticias/lancamento" },
        { icon: "plane", tag: "Missão", date: "Em breve · Mascate", h: "Missão Empresarial a Omã", p: "Delegação de empresas brasileiras para rodadas de negócios nos portos de Duqm, Sohar e Salalah." },
        { icon: "monitor", tag: "Webinar", date: "Em breve · Online", h: "Como Exportar para o Golfo", p: "Especialistas apresentam oportunidades e caminhos para acessar o mercado do Oriente Médio." },
      ],
    },
    launchArticle: {
      tag: "Lançamento",
      date: "11 de maio de 2026 · Congresso Nacional, Brasília",
      title: "Lançamento Oficial da Câmara de Comércio Brasil–Omã",
      quote: "“Hoje iniciamos uma nova rota de crescimento global. Junte-se à Câmara de Comércio Brasil–Omã.”",
      p1: "Em cerimônia oficial realizada no Congresso Nacional, em Brasília, a Câmara de Comércio Brasil–Omã (CTB) foi oficialmente lançada, reunindo autoridades, lideranças empresariais e representantes institucionais dos dois países.",
      p2: "O evento contou com a posse de Mazin Ali Khalfan Al Wahibi como Presidente da Câmara e a participação do conselheiro internacional Luiz Góes, que destacou a estabilidade política de Omã e seu posicionamento estratégico como porta de entrada para o Oriente Médio.",
      p3: "A iniciativa tem como objetivo facilitar a cooperação entre Brasil e Omã em setores como agricultura, logística, energia, tecnologia e investimentos — consolidando uma nova rota de crescimento econômico entre as duas nações.",
      galleryTitle: "Galeria do evento",
      videoTitle: "Momentos da cerimônia",
      pressTitle: "Na Imprensa",
      backLabel: "Voltar para Notícias",
    },
    contact: {
      eyebrow: "Fale conosco",
      title: "Contato",
      lead: "Quer expandir seus negócios entre o Brasil e Omã ou saber mais sobre a CTB? Envie sua mensagem — retornaremos o quanto antes.",
      emailLabel: "E-mail",
      locationLabel: "Localização",
      address: "Brasília, Brasil · Mascate, Omã",
      quote: "“Conectamos oportunidades. Construímos parcerias.”",
      form: {
        name: "Nome completo",
        namePh: "Seu nome completo",
        email: "E-mail",
        emailPh: "seu@email.com",
        company: "Empresa",
        companyPh: "Nome da sua empresa",
        message: "Mensagem",
        messagePh: "Escreva sua mensagem…",
        submit: "Enviar mensagem",
        sending: "Enviando…",
        ok: "Mensagem enviada com sucesso. Obrigado pelo contato!",
        err: "Não foi possível enviar. Verifique os campos e tente novamente.",
      },
    },
    footer: {
      tagline: "Câmara de Comércio Brasil–Omã",
      about: "Associação civil de direito privado, sem fins lucrativos. União e Prosperidade.",
      navTitle: "Navegação",
      contactTitle: "Contato",
      rights: "Todos os direitos reservados.",
    },
  },

  en: {
    meta: {
      title: "BOCC — Brazil–Oman Chamber of Commerce",
      description:
        "Brazil–Oman Chamber of Commerce (CTB): connecting complementary powers. We promote trade, investment and institutional cooperation between Brazil and the Sultanate of Oman.",
    },
    nav: {
      about: "The Chamber",
      countries: "Brazil & Oman",
      services: "What we do",
      ecosystem: "Ecosystem",
      membership: "Join us",
      news: "News",
      contact: "Contact",
    },
    brand: { tagline: "Brazil–Oman Chamber of Commerce" },
    hero: {
      eyebrow: "Brazil · Sultanate of Oman · 2026",
      titleA: "Connecting ",
      titleAccent: "complementary powers",
      titleB: " in a changing world",
      lead: "CTB is the institutional bridge between Brazil and Oman: we promote trade, investment and strategic cooperation with neutrality, transparency and legal certainty.",
      ctaJoin: "Join the Chamber",
      ctaContact: "Get in touch",
      motto: "“Union and Prosperity”",
      stats: [
        { n: "US$ 2 bn+", l: "in annual bilateral trade" },
        { n: "São Paulo · Muscat", l: "presence in both countries" },
        { n: "London · Dubai", l: "integrated global ecosystem" },
      ],
    },
    heroBridge: {
      eyebrow: "Brazil · Sultanate of Oman · 2026",
      titleA: "",
      titleAccent: "Brazil and Oman",
      titleB: " united by a vision for the future",
      lead: "We connect governments, businesses and investors to strengthen strategic relations, promote trade, investment, innovation and institutional cooperation between two nations united by trust, excellence and shared prosperity.",
      ctaJoin: "Join the Chamber",
      ctaLearn: "Learn more",
      mottoMain: "Unity and Prosperity",
      mottoSub: "Unio et Prosperitas · الاتحاد والازدهار",
    },
    purpose: {
      eyebrow: "Our mission",
      titleLine1: "Connect Nations.",
      titleLine2: "Drive Opportunities.",
      titleAccent: "Build Legacies.",
      lead: "We promote strategic relations between Brazil and Oman through trade, investment, innovation and institutional cooperation, creating lasting connections that strengthen economies, bring cultures closer and generate shared prosperity.",
      pillarsEyebrow: "The Chamber's five pillars",
      items: [
        { icon: "handshake", h: "We connect", p: "We build bridges between governments, businesses and investors to turn opportunities into lasting relationships." },
        { icon: "chart", h: "We promote", p: "We drive trade, investment and innovation with institutional security." },
        { icon: "globe", h: "We strengthen", p: "We bring cultures, markets and leaderships closer to build long-term cooperation." },
        { icon: "scale", h: "We ensure", p: "We act with ethics, compliance, transparency and legal certainty in all relationships." },
        { icon: "laurel", h: "We prosper", p: "We create shared value through sustainable economic development." },
      ],
    },
    strip: [
      { icon: "globe", h: "International recognition", p: "Governments · Embassies · Institutions · Strategic Partners" },
      { icon: "pin", h: "Bilateral cooperation", p: "Trade · Investment · Innovation · Economic Diplomacy" },
      { icon: "network", h: "Global network", p: "Brazil · Oman · GCC · International Markets" },
    ],
    about: {
      eyebrow: "Who we are",
      titleLine1: "A civil association,",
      titleAccent: "non-profit,",
      titleLine3: "institutional in character.",
      p1: "CTB — the Brazil–Oman Chamber of Commerce is a private-law, non-profit civil association created to strengthen and deepen commercial, economic and investment relations between the two nations.",
      p2: "We operate with our own legal personality and full administrative, financial and asset autonomy, always guided by ethics, transparency and institutional neutrality.",
      pillars: [
        { icon: "globe", h: "Mission", p: "To promote, strengthen and deepen commercial, economic and investment relations between Brazil and Oman." },
        { icon: "scale", h: "Principles", p: "Action grounded in ethics, transparency, institutional neutrality and respect for both countries' laws." },
        { icon: "bank", h: "Governance", p: "Own legal personality with full administrative, financial and asset autonomy." },
      ],
    },
    moment: {
      eyebrow: "The global moment of 2026",
      title: "Why now",
      lead: "Geopolitical realignment and the fragmentation of global supply chains have made strategic partnerships based on trust and neutrality more essential than ever.",
      cards: [
        { icon: "🌐", h: "Context", p: "Geopolitical realignment and fragmentation of global supply chains." },
        { icon: "⚡", h: "Challenges", p: "Pressure for food security, energy security and the transition to sustainable economies." },
        { icon: "🤝", h: "Opportunity", p: "Strategic partnerships based on trust and neutrality have become essential." },
      ],
    },
    countries: {
      eyebrow: "Two economies, one synergy",
      title: "Brazil & Oman",
      lead: "Two complementary economies. United by opportunity and a shared future.",
      brazil: {
        flag: "🇧🇷",
        name: "Brazil",
        sub: "Leadership and resilience",
        items: [
          { b: "Geopolitics:", t: "a central voice of the Global South and mediator in forums such as G20 and BRICS+." },
          { b: "Environmental diplomacy:", t: "clean energy matrix as a “diplomatic currency” in the climate transition." },
          { b: "Economic strength:", t: "agribusiness, infrastructure and renewable energy (green hydrogen and offshore wind)." },
          { b: "Foreign trade:", t: "exports projected between US$ 340 and US$ 380 billion, with a US$ 70–90 billion surplus." },
        ],
      },
      oman: {
        flag: "🇴🇲",
        name: "Sultanate of Oman",
        sub: "Stability and strategic vision",
        items: [
          { b: "Diplomacy:", t: "a “friend to all” policy, an essential facilitator of dialogue in the Middle East." },
          { b: "Geopolitics:", t: "an enviable position outside the Strait of Hormuz, ensuring energy security." },
          { b: "Logistics hub:", t: "the ports of Duqm, Sohar and Salalah connecting Asia, Africa and Europe." },
          { b: "Vision 2040:", t: "diversification focused on tourism, mining, technology and green hydrogen." },
        ],
      },
    },
    partnership: {
      eyebrow: "A natural and complementary partnership",
      titleLine1: "Trade Flows",
      titleAccent: "and Synergy",
      lead: "Brazil supplies caloric (food) and mineral energy; Oman supplies the chemical inputs (fertilizers) and energy that sustain Brazil's agricultural power. A “quiet strategic partnership” already exceeding US$ 2 billion per year.",
      flowFrom: {
        flag: "🇧🇷",
        h: "Brazil → Oman",
        p: "Iron ore, animal protein complex (poultry and meat) and sugar.",
      },
      flowTo: {
        flag: "🇴🇲",
        h: "Oman → Brazil",
        p: "Nitrogen fertilizers, refined oil and petrochemical products.",
      },
      exampleLabel: "Case in point:",
      exampleText: "Vale's operation in Sohar as an industrial distribution hub for the Middle East and Asia.",
    },
    video: {
      eyebrow: "Institutional video",
      title: "Get to know CTB",
      lead: "A portrait of the institutional bridge we are building between Brazil and the Sultanate of Oman.",
    },
    services: {
      eyebrow: "What we do",
      titleLine1: "Promotion, Connectivity",
      titleAccent: "and Legal Certainty",
      lead: "A complete structure to enable business between the two countries — from first contact to legal certainty of operations.",
      cards: [
        { icon: "handshake", h: "Exchange", p: "Promotion of trade missions, forums, seminars and bilateral business fairs." },
        { icon: "trending", h: "Intelligence", p: "Studies, reports and sector analyses to identify market opportunities." },
        { icon: "globetech", h: "Culture & Technology", p: "Support for initiatives that facilitate technological exchange between the two countries." },
        { icon: "certificate", h: "Certification", p: "Certification services for export documents and certificates of origin." },
        { icon: "bank", h: "Interlocution", p: "Acting as an institutional interlocutor before government authorities when authorized.", featured: true },
        { icon: "scale", h: "Legal Certainty", p: "Own Arbitration and Mediation Center with independent management, speed and impartiality." },
      ],
    },
    ecosystem: {
      eyebrow: "Our strategic ecosystem",
      titleLine1: "An Integrated",
      titleAccent: "Global Structure",
      lead: "CTB's success is supported by an ecosystem of companies and institutions that provide legal, financial, operational and humanitarian support on a global scale.",
      cards: [
        { logo: "/ecosystem/ctb-holdings.png", tag: "London", h: "CTB Holdings", p: "Global holding of the Group, responsible for corporate governance and international strategic guidelines." },
        { logo: "/ecosystem/ctb-venture.png", tag: "Trade Finance", h: "CTBX Venture Investment S.A.", p: "Specialized arm in Trade Finance and commodities consulting, focused on structured operations." },
        { logo: "/ecosystem/omanbrasil.png", tag: "Intelligence", h: "OmanBrasil", p: "Commercial intelligence hub: opportunity identification, market analysis and business intermediation." },
        { logo: "/ecosystem/fundacao-wahibi.png", tag: "ESG · Impact", h: "Wahibi Foundation", p: "Pillar of institutional responsibility in humanitarian projects, sustainability and human development." },
      ],
    },
    membership: {
      eyebrow: "Be part of it",
      titleLine1: "A bridge to",
      titleAccentLine1: "new",
      titleAccentLine2: "opportunities",
      lead: "Become a member and access an exclusive network of business, market intelligence and legal certainty between Brazil and Oman.",
      benefits: [
        { icon: "briefcase", text: "Access to business rounds and corporate missions" },
        { icon: "trending", text: "Exclusive market reports and analyses" },
        { icon: "certificate", text: "Support in certification and foreign trade" },
        { icon: "people", text: "Networking with leaders from both countries" },
        { icon: "scale", text: "Access to the Arbitration and Mediation Center" },
        { icon: "megaphone", text: "Promotion of your company across the Chamber's channels" },
      ],
      cta: "I want to join",
    },
    membershipPage: {
      hero: {
        eyebrow: "Be part of it",
        title: "Join the Brazil–Oman Chamber of Commerce",
        p1: "Become part of a strategic network of companies, investors, institutions and leaders committed to strengthening economic relations between Brazil and the Sultanate of Oman.",
        p2: "As a member, your company gains access to market intelligence, qualified connections, cooperation opportunities and institutional support to develop business between the two countries.",
        cta: "Apply for membership",
        formTitle: "Register your company",
        form: {
          name: "Full name",
          phone: "Phone",
          email: "Professional email",
          company: "Company",
          role: "Role",
          sector: "Industry sector",
          country: "Country",
          message: "Message",
          submit: "Send application",
          sending: "Sending…",
          ok: "Application sent successfully. Our team will be in touch soon!",
          err: "Could not send. Please check the fields and try again.",
        },
      },
      tabs: {
        home: "Home",
        overview: "Benefits",
        understand: "Understand Membership",
        reputation: "Reputation",
        support: "Support",
        connection: "Connection",
        expansion: "Expansion",
        extra: "Services",
        consulting: "Consulting",
      },
      overview: {
        eyebrow: "A network of opportunities",
        title: "Benefits of membership",
        lead: "Membership in the Chamber provides access to an institutional environment created to bring markets closer, identify opportunities and support companies interested in commercial relations between Brazil and Oman.",
        subtitle: "Main benefits",
        items: [
          { icon: "network", h: "Qualified business connections", p: "Access to companies, investors, suppliers, buyers and potential partners in both countries." },
          { icon: "trending", h: "Market intelligence", p: "Access to economic information, sector analyses and opportunities relevant to decision-making." },
          { icon: "plane", h: "Missions and business events", p: "Participation in trade missions, forums, seminars, institutional meetings and business rounds." },
          { icon: "globe", h: "Internationalization support", p: "Initial guidance for companies interested in accessing the Brazilian and Omani markets." },
          { icon: "megaphone", h: "Institutional promotion", p: "Possibility of presenting the company across the Chamber's channels, events and initiatives." },
          { icon: "handshake", h: "Institutional relationship", p: "Participation in a dialogue network with business associations, entities and leaders from both countries." },
          { icon: "certificate", h: "Member certificate", p: "Institutional document recognizing the company's participation in the Chamber's network." },
          { icon: "seal", h: "Digital member seal", p: "Visual identification for use across the company's institutional channels, per the Chamber's guidelines." },
        ],
      },
      understand: {
        eyebrow: "A long-term partnership",
        title: "Understand Membership",
        p1: "Membership is the institutional bond between the Chamber and companies, organizations and professionals who share an interest in expanding economic relations between Brazil and Oman.",
        p2: "More than a benefits program, it represents entry into an ecosystem of cooperation, knowledge and opportunity development.",
        subtitle: "Advantages of Membership",
        lead: "Being a member means expanding your company's relationship capacity, getting to know both markets better and taking part in initiatives focused on trade, investment and bilateral cooperation.",
        items: [
          { icon: "pin", h: "Bilateral presence", p: "Action focused on bringing Brazil and the Sultanate of Oman closer, with connections in Brasília, Muscat and other strategic hubs." },
          { icon: "network", h: "International business network", p: "Relationships with companies, investors, institutions and leaders interested in initiatives between the two countries." },
          { icon: "globetech", h: "Specialized knowledge", p: "Access to information on strategic sectors, the business environment, commercial opportunities and cultural traits of each market." },
          { icon: "bank", h: "Institutional support", p: "Guidance and facilitation of contacts within the Chamber's institutional limits and mandate." },
        ],
      },
      sections: [
        {
          eyebrow: "Reputation",
          number: "1",
          title: "Strengthen your company's institutional presence",
          lead: "By joining the Brazil–Oman Chamber of Commerce, your company becomes part of a network committed to ethics, transparency, cooperation and sustainable economic development.",
          items: [
            { icon: "certificate", h: "Institutional member certificate", p: "Document issued by the Chamber formally recognizing the company's participation in its membership base." },
            { icon: "seal", h: "Exclusive member seal", p: "Visual identity intended for member companies, in line with brand usage guidelines." },
            { icon: "idcard", h: "Profile in the member directory", p: "Institutional presentation of the company in the environment intended for the member network." },
            { icon: "handshake", h: "Participation in Chamber initiatives", p: "Possibility of joining events, forums, missions and projects related to the company's sector." },
            { icon: "megaphone", h: "Promotion of relevant initiatives", p: "Sharing of the company's news, projects and opportunities, subject to the Chamber's editorial criteria." },
            { icon: "calendar", h: "Access to the institutional calendar", p: "Advance information on events, meetings, trade missions and Chamber activities." },
          ],
        },
        {
          eyebrow: "Support",
          number: "2",
          title: "Access opportunities between Brazil and Oman",
          lead: "The Chamber brings together knowledge, connections and initiatives to help companies understand the markets and identify paths for cooperation between the two countries.",
          items: [
            { icon: "trending", h: "Economic data and indicators", p: "Information on bilateral trade, priority sectors, trends and emerging opportunities." },
            { icon: "globe", h: "Knowledge of local markets", p: "Content on the business environment, commercial practices, cultural aspects and traits of each country." },
            { icon: "handshake", h: "Connection facilitation", p: "Identification and initial approach with companies, organizations and potential business partners." },
            { icon: "calendar", h: "Presence at strategic events", p: "Access to forums, conferences, seminars, business meetings and institutional missions." },
          ],
        },
        {
          eyebrow: "Connection",
          number: "3",
          title: "Expand your network of business and partners",
          lead: "The Chamber creates environments favorable to relationships between Brazilian and Omani companies, contributing to new partnerships, projects and business opportunities.",
          items: [
            { icon: "people", h: "Business matchmaking", p: "Identification of companies with complementary interests for possible meetings and negotiations." },
            { icon: "idcard", h: "Member directory", p: "Access to members' institutional information, respecting the network's privacy and usage rules." },
            { icon: "network", h: "Bilateral and international networking", p: "Participation in meetings with business owners, investors, executives and institutional representatives." },
            { icon: "megaphone", h: "Visibility across the Chamber's channels", p: "Possibility of promoting the company, its projects and its opportunities through available institutional channels." },
          ],
        },
        {
          eyebrow: "Expansion",
          number: "4",
          title: "Grow your company's business",
          lead: "Membership provides resources and connections to support companies at different stages of their international expansion.",
          items: [
            { icon: "handshake", h: "Business rounds", p: "Participation in meetings organized with potential buyers, suppliers, investors and partners." },
            { icon: "plane", h: "Business missions", p: "Integration into delegations and trade agendas held in Brazil and Oman." },
            { icon: "trending", h: "Sector studies and analyses", p: "Access to content focused on sectors with the greatest potential for bilateral cooperation." },
            { icon: "briefcase", h: "Presentation of opportunities", p: "Disclosure of business demands, projects, investment proposals and partnership possibilities." },
            { icon: "monitor", h: "Seminars and training", p: "Events on foreign trade, regulatory environment, business culture, logistics and internationalization." },
            { icon: "people", h: "Cooperation among members", p: "Encouragement of joint projects and partnerships within the Chamber's own network." },
          ],
        },
      ],
      extra: {
        eyebrow: "Member services",
        title: "A structure built to support your journey",
        items: [
          { icon: "mail", h: "Dedicated institutional support", p: "Relationship channel to guide members on the Chamber's activities, events and opportunities." },
          { icon: "calendar", h: "Special conditions at events", p: "Differentiated benefits or conditions at certain activities promoted by the Chamber, when applicable." },
          { icon: "bank", h: "Use of meeting spaces", p: "Access to meeting environments or institutional support, subject to availability and specific rules." },
          { icon: "idcard", h: "Listing in the business directory", p: "Inclusion of the company in the area intended for presenting members." },
          { icon: "people", h: "Participation in thematic committees", p: "Possibility of contributing to working groups related to strategic sectors and topics." },
          { icon: "mail", h: "Exclusive newsletters", p: "Bulletins with news, opportunities, events, missions and economic information." },
          { icon: "calendar", h: "Invitations to institutional gatherings", p: "Participation in receptions, meetings, seminars and agendas promoted or supported by the Chamber." },
          { icon: "network", h: "Support in identifying partners", p: "Initial research and referral of potential companies or institutions related to the member's stated goal." },
        ],
      },
      closing: {
        eyebrow: "A connection that creates value",
        title: "Be part of a new stage in Brazil–Oman relations",
        lead: "Register your company with a network built to bring markets closer, strengthen relations and turn opportunities into lasting partnerships.",
        ctaPrimary: "I want to join",
        ctaSecondary: "Talk to our team",
        quote: "“We connect markets. We bring leaders closer. We build shared prosperity.”",
      },
    },
    consultingPage: {
      eyebrow: "International Consulting",
      title: "Strategic intelligence for business between Brazil, Oman and the Gulf",
      p1: "Our team brings together specialists in international trade, market intelligence, investment and institutional relations to support companies looking to expand their operations into the Gulf countries.",
      p2: "More than consulting, we deliver strategy, qualified connections and tailored solutions to accelerate international business.",
      whyTitle: "Why choose our consulting services?",
      why: [
        "A structure built to generate international results.",
        "Personalized support from specialists.",
        "Strategic planning for entering new markets.",
        "Business intelligence based on real data.",
        "An institutional network built across Brazil, Oman and the Middle East.",
      ],
      solutionsTitle: "Solutions tailored to your company's stage",
      blocks: [
        {
          number: "1",
          icon: "briefcase",
          title: "Personalized Strategic Consulting",
          lead: "Every company has different goals.",
          body: "We develop tailor-made projects for internationalization, investment, exports, imports and business expansion.",
          chipsLabel: "Includes",
          chips: ["International planning", "Business strategy", "Custom studies", "Competitive intelligence", "Expansion roadmap"],
        },
        {
          number: "2",
          icon: "trending",
          title: "Companies starting in international trade",
          lead: "For companies looking to safely start their international operations.",
          body: "We carry out complete studies to identify business opportunities and build a consistent internationalization plan.",
          cardsLabel: "Services",
          cards: [
            { h: "Market Intelligence", p: "A complete analysis of the target market, competition, demand and business potential." },
            { h: "Priority Markets", p: "Identification of the most promising countries for your product or service." },
            { h: "Pricing Strategy", p: "Setting competitive prices considering logistics, taxes, competition and international positioning." },
          ],
        },
        {
          number: "3",
          icon: "scale",
          title: "Compliance and International Regulation",
          body: "We guide your company through all the legal requirements to operate abroad.",
          chipsLabel: "Includes",
          chips: ["Trade regulations", "Customs requirements", "International documentation", "Mandatory certifications", "Trade compliance"],
        },
        {
          number: "4",
          icon: "ship",
          title: "Exporting companies looking to enter the Gulf",
          body: "For Brazilian companies that already export and intend to operate in Oman, the United Arab Emirates, Saudi Arabia, Qatar, Kuwait and Bahrain.",
          cardsLabel: "Specialized studies",
          cards: [
            { h: "Distribution Channels", p: "Identification of the best sales channels, distributors and business partners." },
            { h: "Commercial Adaptation", p: "Guidance on packaging, visual identity, communication and cultural adaptation." },
            { h: "Competitive Intelligence", p: "Mapping of competitors, positioning and differentiation opportunities." },
            { h: "Buyer Network", p: "Identification of importers, distributors and investors." },
          ],
        },
        {
          number: "5",
          icon: "globetech",
          title: "International Expansion",
          lead: "For companies already present in the international market.",
          body: "We develop strategies to expand operations and consolidate presence in the Gulf region.",
          chipsLabel: "Services",
          chips: ["International structuring", "Commercial implementation", "Partner development", "Regional growth"],
          subBlocks: [
            {
              h: "Setting Up Companies in Oman",
              p: "We provide full support for setting up companies in the Sultanate of Oman.",
              chipsLabel: "Includes",
              chips: ["Choice of corporate structure", "Licensing", "Business registration", "Foreign investment", "Institutional support"],
            },
            {
              h: "Setting Up Companies in the United Arab Emirates",
              p: "Full advisory services for setting up in Free Zones or Mainland.",
            },
          ],
        },
        {
          number: "6",
          icon: "plane",
          title: "Business Missions",
          lead: "We connect your company directly with decision-makers.",
          body: "We organize personalized executive agendas according to the company's goals.",
          chipsLabel: "Includes",
          chips: ["Business rounds", "Government meetings", "Meetings with investors", "Technical visits", "Trade missions", "Institutional networking"],
        },
        {
          number: "7",
          icon: "monitor",
          title: "International Intelligence",
          body: "We produce strategic studies to support investment decisions.",
          cards: [
            { h: "Executive Workshops", p: "Training on business culture, international negotiation and business opportunities." },
            { h: "Country Reports", p: "An economic, political, legal and commercial overview of the Gulf markets." },
            { h: "Sector Studies", p: "Industry-specific analyses identifying trends and opportunities." },
          ],
        },
        {
          number: "8",
          icon: "people",
          title: "Business Matchmaking",
          lead: "We connect companies, investors and opportunities.",
          body: "Our exclusive service brings your company closer to the region's key economic players.",
          chipsLabel: "Benefits",
          chips: ["Qualified meetings", "Selection of strategic partners", "Institutional support", "Executive networking", "Business follow-up", "Negotiation tracking"],
        },
      ],
      closing: {
        title: "A strategic partner for your international expansion",
        p: "The Brazil–Oman Chamber of Commerce acts as a business facilitator between Brazilian companies and the Gulf market, offering market intelligence, institutional connections and specialized support to turn opportunities into concrete results.",
      },
      form: {
        eyebrow: "Request a Consultation",
        title: "Take your company to a new international level",
        lead: "Our team is ready to develop a personalized strategy for your expansion into the Sultanate of Oman, the United Arab Emirates and other countries of the Gulf Cooperation Council (GCC).",
        fields: { name: "Name", company: "Company", role: "Role", email: "Email", phone: "Phone", country: "Country" },
        submit: "Send request",
        sending: "Sending…",
        ok: "Request sent successfully. Our team will be in touch soon!",
        err: "Could not send. Please check the fields and try again.",
      },
    },
    news: {
      eyebrow: "Stay informed",
      title: "News & Events",
      lead: "Follow the main initiatives, events and opportunities connecting Brazil and Oman.",
      items: [
        { icon: "calendar", tag: "Launch", date: "2026 · Brasília / Muscat", h: "Official Launch of the Brazil–Oman Chamber of Commerce", p: "“Today we begin a new route of global growth. Join the Brazil–Oman Chamber of Commerce.”", link: "/noticias/lancamento" },
        { icon: "plane", tag: "Mission", date: "Soon · Muscat", h: "Business Mission to Oman", p: "A delegation of Brazilian companies for business rounds at the ports of Duqm, Sohar and Salalah." },
        { icon: "monitor", tag: "Webinar", date: "Soon · Online", h: "How to Export to the Gulf", p: "Experts present opportunities and pathways to access the Middle East market." },
      ],
    },
    launchArticle: {
      tag: "Launch",
      date: "May 11, 2026 · National Congress, Brasília",
      title: "Official Launch of the Brazil–Oman Chamber of Commerce",
      quote: "“Today we begin a new route of global growth. Join the Brazil–Oman Chamber of Commerce.”",
      p1: "At an official ceremony held at Brazil's National Congress, in Brasília, the Brazil–Oman Chamber of Commerce (CTB) was officially launched, bringing together authorities, business leaders and institutional representatives from both countries.",
      p2: "The event included the inauguration of Mazin Ali Khalfan Al Wahibi as Chamber President and the participation of international advisor Luiz Góes, who highlighted Oman's political stability and its strategic position as a gateway to the Middle East.",
      p3: "The initiative aims to facilitate cooperation between Brazil and Oman in sectors such as agriculture, logistics, energy, technology and investment — consolidating a new route for economic growth between the two nations.",
      galleryTitle: "Event gallery",
      videoTitle: "Moments from the ceremony",
      pressTitle: "In the Press",
      backLabel: "Back to News",
    },
    contact: {
      eyebrow: "Get in touch",
      title: "Contact",
      lead: "Want to expand your business between Brazil and Oman or learn more about CTB? Send us a message — we'll get back to you as soon as possible.",
      emailLabel: "Email",
      locationLabel: "Location",
      address: "Brasília, Brazil · Muscat, Oman",
      quote: "“We connect opportunities. We build partnerships.”",
      form: {
        name: "Full name",
        namePh: "Your full name",
        email: "Email",
        emailPh: "you@email.com",
        company: "Company",
        companyPh: "Your company name",
        message: "Message",
        messagePh: "Write your message…",
        submit: "Send message",
        sending: "Sending…",
        ok: "Message sent successfully. Thank you for reaching out!",
        err: "Could not send. Please check the fields and try again.",
      },
    },
    footer: {
      tagline: "Brazil–Oman Chamber of Commerce",
      about: "A private-law, non-profit civil association. Union and Prosperity.",
      navTitle: "Navigation",
      contactTitle: "Contact",
      rights: "All rights reserved.",
    },
  },
};

export type Dict = (typeof content)["pt"];
